### ISSUE TITLE
collect2: fatal error: cannot find ‘ld’ compilation terminated.

### ISSUE THREAD

**Issue by totaltommygun** [xTrayambak/lucem#12]
I'm using an immutable distribution so hopefully that isn't the issue

[system info.txt](https://github.com/user-attachments/files/17285600/system.info.txt)
[lucem logs.txt](https://github.com/user-attachments/files/17285659/lucem.logs.txt)

**Comment by xTrayambak** [comment]
Hi, it seems like you're on Bazzite. Yes, this is probably caused by that. Bazzite isn't meant for programmers and people who frequently compile code from what I've seen, so you'll probably need to compile Lucem on another distro (preferably Fedora, since that's what Bazzite seems to be based on). You could also try entering a [Nix environment](https://nixos.org) and compiling Lucem from there on.

**Comment by totaltommygun** [comment]
> Hi, it seems like you're on Bazzite. Yes, this is probably caused by that. Bazzite isn't meant for programmers and people who frequently compile code from what I've seen, so you'll probably need to compile Lucem on another distro (preferably Fedora, since that's what Bazzite seems to be based on). You could also try entering a [Nix environment](https://nixos.org) and compiling Lucem from there on.

Cheers for the help! it'd be cool if there were a binary either as a flatpak, appimage, or a [homebrew](https://brew.sh/) package for Linux; since regular steam os is also immutable (and a lot others since it seems to be the "future for Linux on the desktop") and can't use this awesome program!

**Comment by xTrayambak** [comment]
I'll look into a flatpak later today.
